In [ ]:
def fun(n):
  if (n>100):
    return n-5
  return fun(fun(n+11));
print(fun(45))    

100


In [ ]:
re.split

In [ ]:
def fun(n):

SyntaxError: ignored

# Data Cleaning and Preparation

In [ ]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
from numpy import nan as NA
data = pd.DataFrame({'k1':['one','two']*3+['two'],
                     'k2':[1,1,2,NA,3,4,4]})
print(data)

    k1   k2
0  one  1.0
1  two  1.0
2  one  2.0
3  two  NaN
4  one  3.0
5  two  4.0
6  two  4.0


In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

k1   k2
0  one  1.0
1  two  1.0
2  one  2.0
3  two  NaN
4  one  3.0
5  two  4.0

In [ ]:
data.fillna(3)

k1   k2
0  one  1.0
1  two  1.0
2  one  2.0
3  two  3.0
4  one  3.0
5  two  4.0
6  two  4.0

In [ ]:
data = pd.DataFrame(np.arange(12).reshape(3,4),
                    index=["ohio","colorado","Newyork"],
                    columns=["one","two","three","four"])
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
Newyork     8    9     10    11

In [ ]:
data.replace([1,6,11],[12,13,14])

one  two  three  four
ohio        0   12      2     3
colorado    4    5     13     7
Newyork     8    9     10    14

In [ ]:
data.rename(index={'ohio':'indiana'},
            columns={'two':'six'})

one  six  three  four
indiana     0    1      2     3
colorado    4    5      6     7
Newyork     8    9     10    11

## Handling Missing Data

In [ ]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

In [ ]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
print(data)
print(data.dropna())

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64
0    1.0
2    3.5
4    7.0
dtype: float64


In [ ]:
print(data)
print(data.notnull())
print(data[data.notnull()])

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64
0     True
1    False
2     True
3    False
4     True
dtype: bool
0    1.0
2    3.5
4    7.0
dtype: float64


In [ ]:
import pandas as pd
from numpy import nan as NA
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
print(data)
cleaned = data.dropna()
#data
print(cleaned)

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0


In [ ]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
data[4]=NA
print(data)

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN


In [ ]:
data.dropna(axis=1, how='all')

NameError: ignored

In [ ]:
import numpy as np
df = pd.DataFrame(np.random.randn(7, 3))
print(df)
df.iloc[:4, 1] = NA
print(df)
df.iloc[:2, 2] = NA
print(df)
df.dropna()
#df.dropna(thresh=2)



          0         1         2
0 -1.541996 -0.970736 -1.307030
1  0.286350  0.377984 -0.753887
2  0.331286  1.349742  0.069877
3  0.246674 -0.011862  1.004812
4  1.327195 -0.919262 -1.549106
5  0.022185  0.758363 -0.660524
6  0.862580 -0.010032  0.050009
          0         1         2
0 -1.541996       NaN -1.307030
1  0.286350       NaN -0.753887
2  0.331286       NaN  0.069877
3  0.246674       NaN  1.004812
4  1.327195 -0.919262 -1.549106
5  0.022185  0.758363 -0.660524
6  0.862580 -0.010032  0.050009
          0         1         2
0 -1.541996       NaN       NaN
1  0.286350       NaN       NaN
2  0.331286       NaN  0.069877
3  0.246674       NaN  1.004812
4  1.327195 -0.919262 -1.549106
5  0.022185  0.758363 -0.660524
6  0.862580 -0.010032  0.050009


0         1         2
4  1.327195 -0.919262 -1.549106
5  0.022185  0.758363 -0.660524
6  0.862580 -0.010032  0.050009

### Filling In Missing Data

In [ ]:
df

0         1         2
0  0.931471       NaN       NaN
1  0.106439       NaN       NaN
2 -2.403414       NaN  0.614550
3 -1.798870       NaN  0.959141
4 -0.638945 -1.347600  0.318766
5  1.441998  1.276788 -1.028322
6 -0.263650 -0.531047 -0.954786

In [ ]:
df.fillna(0)

0         1         2
0  0.931471  0.000000  0.000000
1  0.106439  0.000000  0.000000
2 -2.403414  0.000000  0.614550
3 -1.798870  0.000000  0.959141
4 -0.638945 -1.347600  0.318766
5  1.441998  1.276788 -1.028322
6 -0.263650 -0.531047 -0.954786

In [ ]:
df.fillna({1: 0.5, 2: 1})

0         1         2
0  0.931471  0.500000  1.000000
1  0.106439  0.500000  1.000000
2 -2.403414  0.500000  0.614550
3 -1.798870  0.500000  0.959141
4 -0.638945 -1.347600  0.318766
5  1.441998  1.276788 -1.028322
6 -0.263650 -0.531047 -0.954786

In [ ]:
_ = df.fillna(0,inplace=True)
df

0         1         2
0 -1.662863  0.000000  0.000000
1 -1.051845  0.000000  0.000000
2  1.185187  0.000000 -1.421815
3 -0.684864  0.000000 -0.163778
4 -0.144642 -0.347508  2.572241
5 -0.677744 -1.413710  1.186103
6 -0.332188  0.234321 -0.048030

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df
#print(df.fillna(method='ffill'))
#df.fillna(method='ffill', limit=2)

0         1         2
0 -0.959675 -0.024587 -2.065209
1  1.660036 -0.934929 -1.456368
2  0.765971       NaN  2.162746
3 -1.318331       NaN -0.506515
4  0.089518       NaN       NaN
5  0.053087       NaN       NaN

In [ ]:
print(df.fillna(method='ffill'))

          0         1         2
0 -0.959675 -0.024587 -2.065209
1  1.660036 -0.934929 -1.456368
2  0.765971 -0.934929  2.162746
3 -1.318331 -0.934929 -0.506515
4  0.089518 -0.934929 -0.506515
5  0.053087 -0.934929 -0.506515


In [ ]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Data Transformation

### Removing Duplicates

In [ ]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [ ]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [ ]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
print(data)
#data.drop_duplicates(['k1'])

ValueError: ignored

In [ ]:
print(data)
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [ ]:
lowercased = data['food'].str.lower()
print(lowercased)

print(lowercased.map(meat_to_animal))
data['animal'] = lowercased.map(meat_to_animal)

print(data)

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object
0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object
          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon


In [ ]:
data['food'] = data['food'].map(lambda x: meat_to_animal[x.lower()])
print(data)

     food  ounces  animal
0     pig     4.0     pig
1     pig     3.0     pig
2     pig    12.0     pig
3     cow     6.0     cow
4     cow     7.5     cow
5     pig     8.0     pig
6     cow     3.0     cow
7     pig     5.0     pig
8  salmon     6.0  salmon


### Replacing Values

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], [100, 200])

0      1.0
1    100.0
2      2.0
3    100.0
4    200.0
5      3.0
dtype: float64

In [ ]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [ ]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [ ]:
data.rename(index=str.upper, columns=str.upper)

ONE  TWO  THREE  FOUR
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [ ]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretization and Binning

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [ ]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
print(type(cats))
print(cats)

<class 'pandas.core.arrays.categorical.Categorical'>
[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]


In [ ]:
print(cats.codes)
#cats.categories
#pd.value_counts(cats)

[0 0 0 1 0 0 2 1 3 2 2 1]


In [ ]:
cat = pd.cut(ages, [18, 26, 36, 61, 100], right=False)
print(cat.codes)

[0 0 0 1 0 0 2 1 3 2 2 1]


In [ ]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.25, 0.49], (0.021, 0.25], (0.021, 0.25], (0.72, 0.95], (0.72, 0.95], ..., (0.72, 0.95], (0.25, 0.49], (0.72, 0.95], (0.72, 0.95], (0.25, 0.49]]
Length: 20
Categories (4, interval[float64]): [(0.021, 0.25] < (0.25, 0.49] < (0.49, 0.72] < (0.72, 0.95]]

In [ ]:
data = np.random.randn(1000)  # Normally distributed
cats = pd.qcut(data, 4)  # Cut into quartiles
cats
pd.value_counts(cats)

In [ ]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

### Detecting and Filtering Outliers

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.057161     0.022665    -0.036024     0.044995
std       1.031365     0.982427     1.003212     1.031369
min      -3.356936    -3.160478    -3.516848    -3.537938
25%      -0.618868    -0.644730    -0.692198    -0.595420
50%       0.036131     0.019809    -0.037389     0.085588
75%       0.740578     0.694067     0.596822     0.753993
max       3.075239     3.018301     3.377534     3.367956

In [ ]:
col = data[2]
col[np.abs(col) > 3]

38    -3.349905
272    3.297111
388   -3.092260
572   -3.420474
695    3.377534
872   -3.516848
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(1)]

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

In [ ]:
np.sign(data).head()

NameError: ignored

### Permutation and Random Sampling

In [ ]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.permutation(arr)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
print(df)
sampler

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19


array([1, 3, 4, 2, 0])

In [ ]:
df
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3

In [ ]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15

In [ ]:
choices = np.array([5, 7, -1, 6, 4])
sampler=np.random.randint(0,len(choices),size=10)
sampler
draws = choices.take(sampler)
draws

array([ 6,  7,  7,  7,  4,  5,  7,  4, -1,  7])

### Computing Indicator/Dummy Variables

In [ ]:
import pandas as pd
df = pd.DataFrame({'key': ['5', '2', '1', '3', '1', '2'],
                   'data1': range(6)})
print(df)
pd.get_dummies(df['key'])

  key  data1
0   5      0
1   2      1
2   1      2
3   3      3
4   1      4
5   2      5


1  2  3  5
0  0  0  0  1
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  1  0  0  0
5  0  1  0  0

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='Grade')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  Grade_1  Grade_2  Grade_3  Grade_5
0      0        0        0        0        1
1      1        0        1        0        0
2      2        1        0        0        0
3      3        0        0        1        0
4      4        1        0        0        0
5      5        0        1        0        0

In [ ]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)
movies[:10]

In [ ]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [ ]:
genres

In [ ]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [ ]:
gen = movies.genres[0]
gen.split('|')
dummies.columns.get_indexer(gen.split('|'))

In [ ]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [ ]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

In [ ]:
np.random.seed(12345)
values = np.random.rand(10)
values
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

## String Manipulation

### String Object Methods

In [ ]:
val = 'hi, Hello Everyone, Good Evening'
len(val.split(',')[1])

15

In [ ]:
pieces = [x.strip() for x in val.split(',')]
len(pieces[1])

14

In [ ]:
len(pieces)

3

In [ ]:
first, second, third = pieces
print(first)
first + '::' + second + '::' + third

hi


'hi::Hello Everyone::Good Evening'

In [ ]:
'::'.join(pieces)

'_'.join(pieces)

'hi_Hello Everyone_Good Evening'

In [ ]:
val
'Good' in val
val.index(',')
val.find(':')

-1

In [ ]:
print(val)
print(val.index(':'))

hi, Hello Everyone, Good Evening


ValueError: ignored

In [ ]:
val.count(',')

2

In [ ]:
val.replace(',', '::')
val.replace(',', '')

'hi Hello Everyone Good Evening'

In [ ]:
s1 = ['Sree Vidyanikethan Engineering College', 'Sree Vinayaka Mission', 'Sri padmavathy']


### Regular Expressions

In [ ]:
import re
text = "foo_bar\t baz_ \tqux"
re.split('\s+', text)

['foo_bar', 'baz_', 'qux']

In [ ]:
regex = re.compile('\s+')
regex.split(text)

['foo_bar', 'baz_', 'qux']

In [ ]:
regex.findall(text)

['\t ', ' \t']

In [ ]:
text = """dave_xyz@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
regex.findall(text,0,35)

['dave_xyz@google.com']

In [ ]:
m = regex.search(text)
m
#text[m.start():m.end()]

<re.Match object; span=(10, 24), match='xyz@google.com'>

In [ ]:
text = """davexyz@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9.%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

print(regex.match(text))

<re.Match object; span=(0, 18), match='davexyz@google.com'>


In [ ]:
print(regex.sub('EMAIL', text))

EMAIL
Steve EMAIL
Rob EMAIL
Ryan EMAIL



In [ ]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
m = regex.match('wesm@bright.net')
print(m)
m.groups()

<re.Match object; span=(0, 15), match='wesm@bright.net'>


('wesm', 'bright', 'net')

In [ ]:
regex.findall(text)

[('davexyz', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Vectorized String Functions in pandas

In [ ]:
import numpy as np
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
print(data)
print(data.isnull())

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object
Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool


In [ ]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
pattern
print(type(data))
data.str.findall(pattern, flags=re.IGNORECASE)

<class 'pandas.core.series.Series'>


Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [ ]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [ ]:
type(matches)

pandas.core.series.Series

In [ ]:
print(data)
data.str[0]

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object


Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [ ]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

## Conclusion